apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
  namespace: emp-platform
  labels:
    app: department-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: department-service
  template:
    metadata:
      labels:
        app: department-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: department-service
        image: YOUR_ECR_URI/department-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: DB_URL
          value: "jdbc:postgresql://postgres-dept:5432/deptdb"
        envFrom:
        - configMapRef:
            name: emp-config
        - secretRef:
            name: emp-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: emp-platform
spec:
  selector:
    app: department-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
